<?php 
/**
 * This file is part of Cms
 *
 * (c) 2014 Keon Nguyen <cuongmits@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="block-item">
    <?php if (!is_null($this->blockItemTitle)) { ?>
        <div class="block-item-title"><?php echo $this->blockItemTitle ?></div>
    <?php } ?>
    <ul>
    <?php 
    foreach($this->termTaxonomies as $termTaxonomy) { 
        echo '<li><a href="'.$this->url('home').$termTaxonomy->getTerm()->getSlug().'">'.$termTaxonomy->getTerm()->getName().'</a></li>';
    }?>
    </ul>
</div>