<?php 
/**
 * This file is part of Cms
 *
 * (c) 2014 Keon Nguyen <cuongmits@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<div class="block-item">
    <div class="block-item-title block-login">Login</div>
    <form action="/authen" method="POST" class="form-signin" role="form">
        <input name="username" type="text" class="form-control" placeholder="Username" required="" autofocus="">
        <input name="password" type="password" class="form-control" placeholder="Password" required="">
        <label class="checkbox">
            <input type="hidden" name="rememberme" value="0">
            <input type="checkbox" name="rememberme" value="1"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>

