<?php
$title = 'Unpublish Post';
$this->headTitle($title);?>
<h1><?php echo $this->escapeHTML($title); ?></h1>

<p>Are you sure that you want to unpublish 
  '<?php echo $this->escapeHTML($this->post['postTitle']); ?>' 
</p>
<?php 
$url = $this->url('home/Post', array('action' => 'unpublish', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$this->post['ID']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>