<?php //echo ini_get("session.upload_progress.name"); ?>
<style>
    div.progressbar {
        height: 10px;
        background-color: red;
        width: 0;
    }
    div.fullProgressbar {
        height: 10px;
        background-color: green;
        width: 100%;
    }
</style>
<script>
/* Script written by Adam Khoury @ DevelopPHP.com */
/* Video Tutorial: http://www.youtube.com/watch?v=EraNFJiY0Eg */
function _(el){
	return document.getElementById(el);
}
function uploadFile(){
    //var formdata = new FormData();
    /*
    var file = _("image-file").files[0];
    console.log(file);
    //alert(file.name+" | "+file.size+" | "+file.type);
    formdata.append("image-file", file);
    */
    var fileInput = document.getElementById('image-file');
    for (var i=0; i<fileInput.files.length; ++i) {
        var li = $("<li>" + fileInput.files[i].name + "<div class='fullProgressbar'><div class='progressbar'></div></div><div class='uploadMessage'></div></li>");
        $("#progress-bar").append(li);
        li.hide().fadeIn();
        
        var formdata = new FormData();
        
        formdata.append("image-file", fileInput.files[i]);
        console.log(fileInput.files[i]);
    
        var ajax = new XMLHttpRequest();
        ajax.upload.li = li;
        //ajax.upload.addEventListener("progress", progressHandler, false);
        ajax.upload.addEventListener("progress", function(event) {
            var percent = (event.loaded / event.total) * 100;
            this.li.find(".progressbar").width(percent+'%');
        }, false);
        
        ajax.li = li;
        //ajax.addEventListener("load", completeHandler, false);
        ajax.addEventListener("load", function(event) {
            console.log('ok');
            console.log(event);
            response = JSON.parse(event.target.responseText);
            //this.li.find('.uploadMessage').innerHTML = response.res;
            this.li.find('.uploadMessage').append(response.res);
        }, false);
        //ajax.addEventListener("error", errorHandler, false);
        ajax.addEventListener("error", function(event) {
            this.li.find('.uploadMessage').append("Upload Failed");
        }, false);
        //ajax.addEventListener("abort", abortHandler, false);
        ajax.addEventListener("abort", function(event) {
            this.li.find('.uploadMessage').append("Upload Aborted");
        }, false);
        url = 'http://localhost/media/upload-progress2';
        ajax.open("POST", url);
        //ajax.open("POST", "file_upload_parser.php");
        ajax.send(formdata);
    }
}
function progressHandler(event){
        console.log('progressHandler');
        console.log(event);
	_("loaded_n_total").innerHTML = "Uploaded "+event.loaded+" bytes of "+event.total;
	var percent = (event.loaded / event.total) * 100;
	_("progressBar").value = Math.round(percent);
	_("status").innerHTML = Math.round(percent)+"% uploaded... please wait";
}
function completeHandler(event){
    console.log("completeHandler");
        console.log(event);
        response = JSON.parse(event.target.responseText);
	//_("status").innerHTML = event.target.responseText;
        _("status").innerHTML = response.res;
        //_("status").innerHTML = '';
	_("progressBar").value = 0;
}
function errorHandler(event){
	_("status").innerHTML = "Upload Failed";
}
function abortHandler(event){
	_("status").innerHTML = "Upload Aborted";
}
</script>
<h2>HTML5 File Upload Progress Bar Tutorial</h2>
<!--
<form id="upload_form" enctype="multipart/form-data" method="post">
  <input type="file" name="file1" id="file1"><br>
  <input type="button" value="Upload File" onclick="uploadFile()">
  <progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
  <h3 id="status"></h3>
  <p id="loaded_n_total"></p>
</form>
-->

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
    <?php $fileElement = $form->get('image-file'); ?>
    <?php echo $this->formFile($fileElement); ?>
    <?php echo $this->formElementErrors($fileElement); ?>
    <input type="button" value="Upload File">
    <progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
    <div id="progress-bar"></div>
    <h3 id="status"></h3>
    <!--<p id="loaded_n_total"></p>-->
<?php echo $this->form()->closeTag(); ?>
