<?php
/**
 * This file is part of Cms
 *
 * (c) 2014 Keon Nguyen <cuongmits@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$title = "Login";
$this->headTitle($title);
if (null!=$this->identity()) { //if logged in
    $user = $this->identity();
    echo 'Logged in as ' . $this->escapeHtml($user->getUserLogin()); ?>
    | <a href="<?php echo $this->url('home/Dashboard', array('controller' => 'dashboard', 'action' => 'index')); ?>">
        <?php echo 'Control Panel'; ?></a> 
    | <a href="<?php echo $this->url('home/Authen', array('controller' => 'authen', 'action' => 'logout')); ?>">
        <?php echo 'Logout'; ?></a> 
    <?php
} else { //if not ?>
    <h1><?php echo $title; ?> <small>you're not logged in!</small></h1>
<?php
if ($this->message)
    echo '<div class="bs-callout bs-callout-warning">'.$this->escapeHTML($this->message).'</div>';

$form = $this->form;
$form->setAttribute('action', $this->url('home/Authen', array('action', 'login',)));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
?>
<div class="form-group">
    <?php
    $form->get('username')->setAttribute('class', 'form-control');
    $form->get('username')->setAttribute('id', 'username');
    echo $this->formRow($form->get('username')) . PHP_EOL;
    ?>
</div>
<div class="form-group">
    <?php
    $form->get('password')->setAttribute('class', 'form-control');
    $form->get('password')->setAttribute('id', 'password');
    echo $this->formRow($form->get('password')) . PHP_EOL;
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('rememberme')) . PHP_EOL;
    ?>
</div>
<?php
$form->get('submit')->setAttribute('class', 'btn btn-default'); //for style
echo $this->formRow($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag(); 
}?>