<?php 
/**
 * This file is part of Cms
 *
 * (c) 2014 Keon Nguyen <cuongmits@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$this->headScript()
        ->appendFile($this->basePath() . '/ckeditor/ckeditor.js');
$title = 'All Comments';
$this->headTitle($title); 
//var_dump($this->posts);
//var_dump($this->test);
//var_dump($this->test);
?>
<h1><?php echo $this->escapeHTML($title); ?></h1>
<div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
        <strong>All</strong><small>(<?php echo $this->comments_quantity; ?>)</small> 
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'pending', 'controller' => 'Comment')); ?>'>Pending</a><small>(<?php echo $this->pending_comments_quantity; ?>)</small> 
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'approved', 'controller' => 'Comment')); ?>'>Approved</a><small>(<?php echo $this->approved_comments_quantity; ?>)</small> 
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'spam', 'controller' => 'Comment')); ?>'>Spam</a><small>(<?php echo $this->spam_comments_quantity; ?>)</small>
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'trash', 'controller' => 'Comment')); ?>'>Trash</a><small>(<?php echo $this->trash_comments_quantity; ?>)</small>
    </div>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
        <form class="navbar-form navbar-right">
            <div class='row'>
                <div class='col-xs-12 col-sm-12 col-md-6 col-lg-7'>
                    <input type="text" class="form-control post-search" placeholder="Search...">
                </div>
                <div class='col-xs-12 col-sm-12 col-md-6 col-lg-5'>
                    <input name="submit" type="submit" value="Search Posts" class='btn btn-default'>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
  <table class="table table-hover">
      <thead>
          <tr>
              <th><input type="checkbox"></th>
              <th>Author</th>
              <th>Comment</th>
              <th>In Response To</th>
              <th>#</th>
          </tr>
      </thead>
      <tfoot>
          <tr>
              <th><input type="checkbox"></th>
              <th>Author</th>
              <th>Comment</th>
              <th>In Response To</th>
              <th>#</th>
          </tr>
      </tfoot>
      <tbody>
          <?php
          foreach ($this->comments as $comment) {
              echo '<tr>';
              echo '<td><input type="checkbox" value="'.$comment->comment_ID.'"></td>';
              echo '<td>'.$comment->comment_author
                      .'<small><br /><a href="mailto:'.$comment->comment_author_email.'">'.$comment->comment_author_email.'</a><br />'. $comment->comment_author_IP.'</small></td>' ;
              echo '<td><small>Submitted on '.$comment->comment_date.'</small><br />'.$comment->comment_content.'</td>' ;
              echo '<td><span class="badge">n</span> comments in post #'.$comment->comment_post_ID.' (View)</td>' ;
              echo '<td>';
              if ($comment->comment_approved=='1') //approved
                echo '<a href="'.$this->url('home/Comment', array(
                    'action' => 'unapprove',
                    'id' => $comment->comment_ID,
                )).'">Unapprove</a>';
              elseif ($comment->comment_approved=='0') //pending
                echo '<a href="'.$this->url('home/Comment', array(
                    'action' => 'approve',
                    'id' => $comment->comment_ID,
                )).'">Approve</a>';
              echo ' | <a href="'.$this->url('home/Comment', array(
                  'action' => 'reply',
                  'id' => $comment->comment_ID,
              )).'">Reply</a>';
              echo ' | <a href="'.$this->url('home/Comment', array(
                  'action' => 'edit',
                  'id' => $comment->comment_ID,
              )).'">Edit</a>';
              echo ' | <a href="'.$this->url('home/Comment', array(
                  'action' => 'doSpam',
                  'id' => $comment->comment_ID,
              )).'">Spam</a>';
              echo ' | <a href="'.$this->url('home/Comment', array(
                  'action' => 'doTrash',
                  'id' => $comment->comment_ID,
              )).'">Trash</a>';
              echo '</td>';
              echo '</tr>';
          }?>
      </tbody>
  </table>
<?php 
echo $this->paginationControl($this->comments,'Sliding','search_pagination.phtml',array(
    'route' => 'home/Comment', 'controller' => 'Comment', 'actionName' => 'all')); ?>
</div>