<?php
$title = 'Delete Page Permanently';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHTML($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHTML($this->post['postTitle']); ?>' permanently?
</p>
<?php 
$url = $this->url('home/Page', array('action' => 'deletePermanently', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$this->post['ID']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>