<?php 
$this->headScript()
        ->appendFile($this->basePath() . '/ckeditor/ckeditor.js');
$title = 'Trash Comments';
$this->headTitle($title); 
//var_dump($this->posts);
//var_dump($this->test);
//var_dump($this->test);
?>
<h1><?php echo $this->escapeHTML($title); ?></h1>
<div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
        <a href='<?php echo $this->url('home/Comment', array('action' => 'all', 'controller' => 'Comment')); ?>'>All</a><small>(<?php echo $this->all_comments_quantity; ?>)</small>
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'pending', 'controller' => 'Comment')); ?>'>Pending</a><small>(<?php echo $this->pending_comments_quantity; ?>)</small> 
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'approved', 'controller' => 'Comment')); ?>'>Approved</a><small>(<?php echo $this->approved_comments_quantity; ?>)</small> 
        | <a href='<?php echo $this->url('home/Comment', array('action' => 'spam', 'controller' => 'Comment')); ?>'>Spam</a><small>(<?php echo $this->spam_comments_quantity; ?>)</small>
        | <strong>Trash</strong><small>(<?php echo $this->trash_comments_quantity; ?>)</small>
    </div>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
        <form class="navbar-form navbar-right">
            <div class='row'>
                <div class='col-xs-12 col-sm-12 col-md-6 col-lg-7'>
                    <input type="text" class="form-control post-search" placeholder="Search...">
                </div>
                <div class='col-xs-12 col-sm-12 col-md-6 col-lg-5'>
                    <input name="submit" type="submit" value="Search Posts" class='btn btn-default'>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
  <table class="table table-hover">
      <thead>
          <tr>
              <th><input type="checkbox"></th>
              <th>Author</th>
              <th>Comment</th>
              <th>In Response To</th>
              <th>#</th>
          </tr>
      </thead>
      <tfoot>
          <tr>
              <th><input type="checkbox"></th>
              <th>Author</th>
              <th>Comment</th>
              <th>In Response To</th>
              <th>#</th>
          </tr>
      </tfoot>
      <tbody>
          <?php
          foreach ($this->comments as $comment) {
              echo '<tr>';
              echo '<td><input type="checkbox" value="'.$comment->comment_ID.'"></td>';
              echo '<td>'.$comment->comment_author.'<br /><a href="mailto:'.$comment->comment_author_email.'"><br />'. $comment->comment_author_IP.'</td>' ;
              echo '<td><small>Submitted on '.$comment->comment_date.'</small><br />'.$comment->comment_content.'</td>' ;
              echo '<td><span class="badge">n</span> comments in post #'.$comment->comment_post_ID.' (View)</td>' ;
              echo '<td>';
              echo '<a href="'.$this->url('home/Comment', array(
                  'action' => 'unTrash',
                  'id' => $comment->comment_ID,
              )).'">Restore</a>';
              echo ' | <a href="'.$this->url('home/Comment', array(
                  'action' => 'delete',
                  'id' => $comment->comment_ID,
              )).'">Delete Permanently</a>';
              echo '</td>';
              echo '</tr>';
          }?>
      </tbody>
  </table>
<?php 
echo $this->paginationControl($this->comments,'Sliding','search_pagination.phtml',array(
    'route' => 'home/Comment', 'controller' => 'Comment', 'actionName' => 'trash')); ?>
</div>