<?php
$title = 'Delete User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHTML($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHTML($this->user->getUserLogin()); ?>' forever?
</p>
<?php 
$url = $this->url('home/User', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->user->getId(); ?>" />
        <div class="form-group delete_option">
            <label>
                <input type="radio" id="delete_option0" name="delete_option" value="delete_all_posts">
                Delete all posts
            </label>
        </div>
        <div class="form-group delete_option">
            <label>
                <input type="radio" id="delete_option0" name="delete_option" value="attribute_all_posts">
                Attribute all posts
                <select name="target_user_id" id="target_user_id" class="">
                    <?php
                    foreach ($this->allUsers as $user) {
                        echo '<option value="'.$user->getId().'">'.$user->getUserLogin().'</option>';
                    }
                    ?>
                </select>
            </label>
        </div>
        <input type="submit" name="submit" id="submit" class="button" value="Confirm Deletion">
    </div>
</form>